version: '3.7'

services:

  mysql-master:
    image: mysql:8
    command:
      - --default_authentication_plugin=mysql_native_password
      - --gtid_mode=ON
      - --enforce_gtid_consistency=ON
      - --relay-log=relay-bin
      - --server_id=1
    environment: &environment
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
      MYSQL_REPLICATION_USER: repl
      MYSQL_REPLICATION_PASSWORD: pass
    ports:
      - 13306:3306
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro

  mysql-slave:
    image: mysql:8
    depends_on:
      - mysql-master
    command:
      - --default_authentication_plugin=mysql_native_password
      - --gtid_mode=ON
      - --enforce_gtid_consistency=ON
      - --relay-log=relay-bin
      - --server_id=2
    environment:
      <<: *environment
      MYSQL_REPLICATION_HOST: mysql-master
    ports:
      - 23306:3306
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro
