#!/bin/bash

if [ -v MYSQL_REPLICATION_USER -a -v MYSQL_REPLICATION_PASSWORD ]; then
  mysql -u root -v mysql <<SQL
    CREATE USER '$MYSQL_REPLICATION_USER'@'%' IDENTIFIED BY '$MYSQL_REPLICATION_PASSWORD';
    GRANT REPLICATION SLAVE ON *.* TO '$MYSQL_REPLICATION_USER'@'%';
SQL
fi

mysql -u root -v mysql <<SQL
  RESET MASTER;
SQL

if [ -v MYSQL_REPLICATION_USER -a -v MYSQL_REPLICATION_PASSWORD -a -v MYSQL_REPLICATION_HOST ]; then
  mysqladmin ping --wait=5 -h "$MYSQL_REPLICATION_HOST"
  mysql -u root -v <<SQL
    CHANGE MASTER TO
      MASTER_HOST = '$MYSQL_REPLICATION_HOST',
      MASTER_USER = '$MYSQL_REPLICATION_USER',
      MASTER_PASSWORD = '$MYSQL_REPLICATION_PASSWORD',
      MASTER_AUTO_POSITION = 1,
      MASTER_DELAY = 10;
    START SLAVE;
SQL
fi
